name: mealsApp
description: A catalogue of restaurants and eateries in Malawi.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
    sdk: ">=2.10.0-0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    font_awesome_flutter: ^8.8.1
    firebase_core: ^0.7.0
    firebase_auth: ^0.20.1
    firebase_storage: ^7.0.0
    cloud_firestore: ^0.16.0+1
    cached_network_image: ^2.5.1
    firebase_image:
        git:
            url: git://github.com/thearaks/firebase_image.git
            ref: feature/firebase_storage_6
    bloc: ^6.0.0
    flutter_bloc: ^6.0.0
    auto_animated: ^2.1.0
    delayed_display: ^1.1.0
    flutter_staggered_grid_view: ^0.3.4
    loading_indicator: ^1.2.0
    photo_view: ^0.10.3
    flutter_sliding_up_panel: ^1.2.1
    carousel_slider: ^3.0.0
    alphabet_list_scroll_view: ^1.0.6
    gradient_text: ^1.0.2
    animated_splash_screen: ^1.0.1+2
    url_launcher: ^5.7.10
    shared_preferences: ^0.5.12+4

    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
    cupertino_icons: ^0.1.3

dev_dependencies:
    flutter_test:
        sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true

    # To add assets to your application, add an assets section, like this:
    assets:
        - assets/images/
    #   - images/a_dot_ham.jpeg

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    fonts:
        - family: Oxygen
          fonts:
              - asset: assets/fonts/Oxygen-Bold.ttf
                weight: 700
              - asset: assets/fonts/Oxygen-Light.ttf
                weight: 300
              - asset: assets/fonts/Oxygen-Regular.ttf
                weight: 400
        - family: AllertaStencil
          fonts:
              - asset: assets/fonts/AllertaStencil-Regular.ttf
                weight: 400
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
